# Generated by Django 5.2.3 on 2025-06-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='eventcategory',
            old_name='event_id',
            new_name='event',
        ),
    ]
