# Generated by Django 5.2.7 on 2025-11-17 10:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventattendee",
            unique_together={("event", "user")},
        ),
    ]
