# Generated by Django 5.2.7 on 2025-11-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_eventattendee_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendee_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
