# Generated by Django 5.2.7 on 2025-11-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_attendee_count_event_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
