# Generated by Django 5.2.7 on 2025-11-26 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_event_capacity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="attendee_count",
        ),
    ]
