# Generated by Django 5.2.7 on 2025-10-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(default="default.jpg", upload_to="profile_images/"),
        ),
    ]
