# Generated by Django 5.2.7 on 2025-10-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
