# Generated by Django 5.2.7 on 2025-11-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="avatars/default.svg",
                null=True,
                upload_to="avatars/",
            ),
        ),
    ]
