# Generated by Django 5.2.7 on 2025-11-17 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["sent_at"]},
        ),
    ]
